<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2452" started-at="2014-08-27T16:09:25Z" finished-at="2014-08-27T16:09:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2452" started-at="2014-08-27T16:09:25Z" finished-at="2014-08-27T16:09:28Z">
      <class name="com.sirma.itt.javacourse.server.ServerTest">
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.sirma.itt.javacourse.server.ServerTest@ceb1a5]" name="initialize" is-config="true" duration-ms="43" started-at="2014-08-27T19:09:25Z" finished-at="2014-08-27T19:09:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="testClient()[pri:0, instance:com.sirma.itt.javacourse.server.ServerTest@ceb1a5]" name="testClient" duration-ms="1037" started-at="2014-08-27T19:09:25Z" finished-at="2014-08-27T19:09:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testClient -->
        <test-method status="FAIL" signature="testSratingTheServer()[pri:0, instance:com.sirma.itt.javacourse.server.ServerTest@ceb1a5]" name="testSratingTheServer" duration-ms="1317" started-at="2014-08-27T19:09:26Z" finished-at="2014-08-27T19:09:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<false> but was:<true>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<false> but was:<true>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:185)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:192)
	at com.sirma.itt.javacourse.server.ServerTest.testSratingTheServer(ServerTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSratingTheServer -->
      </class> <!-- com.sirma.itt.javacourse.server.ServerTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
